# Generated by Django 3.1.7 on 2021-02-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20210225_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
